/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gEmbedded_nativeinterface_GPIOController */

#ifndef _Included_com_comert_gEmbedded_nativeinterface_GPIOController
#define _Included_com_comert_gEmbedded_nativeinterface_GPIOController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    setPinFunction
 * Signature: (Lcom/comert/gEmbedded/api/device/gpio/pin/Pin;Lcom/comert/gEmbedded/api/device/gpio/pin/PinFunction;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_setPinFunction
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    setPullUpDownStatus
 * Signature: (Lcom/comert/gEmbedded/api/device/gpio/pin/Pin;Lcom/comert/gEmbedded/api/device/gpio/pin/PullUpDownStatus;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_setPullUpDownStatus
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    setEventDetectStatus
 * Signature: (Lcom/comert/gEmbedded/api/device/gpio/pin/Pin;Lcom/comert/gEmbedded/api/device/gpio/pin/EventDetectStatus;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_setEventDetectStatus
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    getRegisterSelector
 * Signature: (Lcom/comert/gEmbedded/api/device/gpio/pin/Pin;)I
 */
JNIEXPORT jint JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_getRegisterSelector
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    getPinSet
 * Signature: (Lcom/comert/gEmbedded/api/device/gpio/pin/Pin;)I
 */
JNIEXPORT jint JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_getPinSet
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    isHigh
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_isHigh
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    isLow
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_isLow
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    write
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_write
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    clear
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_clear
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    pulse
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_pulse
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    poll
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_poll
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_GPIOController
 * Method:    releaseGPIOThreadRecourse
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_GPIOController_releaseGPIOThreadRecourse
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
