/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gEmbedded_nativeinterface_DeviceController */

#ifndef _Included_com_comert_gEmbedded_nativeinterface_DeviceController
#define _Included_com_comert_gEmbedded_nativeinterface_DeviceController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gEmbedded_nativeinterface_DeviceController
 * Method:    setupDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_DeviceController_setupDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_DeviceController
 * Method:    shutdownDevice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_nativeinterface_DeviceController_shutdownDevice
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_DeviceController
 * Method:    getNotSupportedPins
 * Signature: ()Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_com_comert_gEmbedded_nativeinterface_DeviceController_getNotSupportedPins
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gEmbedded_nativeinterface_DeviceController
 * Method:    getNotSupportedI2CBusses
 * Signature: ()Ljava/util/Set;
 */
JNIEXPORT jobject JNICALL Java_com_comert_gEmbedded_nativeinterface_DeviceController_getNotSupportedI2CBusses
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
