/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_comert_gEmbedded_pi_nativeinterface_DeviceController */

#ifndef _Included_com_comert_gEmbedded_pi_nativeinterface_DeviceController
#define _Included_com_comert_gEmbedded_pi_nativeinterface_DeviceController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_comert_gEmbedded_pi_nativeinterface_DeviceController
 * Method:    setUpJNIDriver
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_pi_nativeinterface_DeviceController_setUpJNIDriver
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_comert_gEmbedded_pi_nativeinterface_DeviceController
 * Method:    shutDownJNIDriver
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_pi_nativeinterface_DeviceController_shutDownJNIDriver
  (JNIEnv *, jclass);

/*
 * Class:     com_comert_gEmbedded_pi_nativeinterface_DeviceController
 * Method:    setUpGpioDriver
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_pi_nativeinterface_DeviceController_setUpGpioDriver
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_comert_gEmbedded_pi_nativeinterface_DeviceController
 * Method:    shutDownGpioDriver
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_pi_nativeinterface_DeviceController_shutDownGpioDriver
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_comert_gEmbedded_pi_nativeinterface_DeviceController
 * Method:    setUpI2CMasterDriver
 * Signature: (Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_pi_nativeinterface_DeviceController_setUpI2CMasterDriver
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     com_comert_gEmbedded_pi_nativeinterface_DeviceController
 * Method:    shutDownI2CMasterDriver
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_comert_gEmbedded_pi_nativeinterface_DeviceController_shutDownI2CMasterDriver
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
